Repository Loopz-Official/Loopz-FE, pull requests merged in 2025-07, with the labels that each got.

#33 Fix: 브랜딩 페이지 기획 요구사항 반영
  apps/client/src/assets/header/loopz.svg
  apps/client/src/components/features/about/ContactButton.tsx
  apps/client/src/components/features/about/ContactSection.tsx
  apps/client/src/components/features/about/ProjectSection.tsx
Labels: ✨ feature, 🧑‍🔧 fix

#34 Feat: 장바구니 UI 구현
  apps/client/public/cart-item.jpg
  apps/client/src/app/address/AddressPageContent.tsx
  apps/client/src/app/cart/layout.tsx
  apps/client/src/app/cart/page.tsx
  apps/client/src/components/common/BottomNotice.tsx
  apps/client/src/components/common/CheckBox.tsx
  apps/client/src/components/common/EditDeleteButton.tsx
  apps/client/src/components/common/VerticalDivider.tsx
  apps/client/src/components/features/cart/CartItem.tsx
  apps/client/src/components/features/cart/CartSummary.tsx
  apps/client/src/components/features/cart/EmptyCart.tsx
  apps/client/src/components/features/cart/ObjeSelectBar.tsx
  apps/client/src/components/features/cart/PurchaseNowButton.tsx
  apps/client/src/components/features/obje/BottomSheet.tsx
  apps/client/src/components/features/order/form/AgreementSection.tsx
  apps/client/src/components/layouts/Header.tsx
  apps/client/src/constants/cartSummary.ts
  apps/client/src/constants/header.ts
  apps/client/src/constants/helperText.ts
  apps/client/vercel.json
Labels: 📷 UI

#45 Fix: Add Suspense boundary for useSearchParams hook
  apps/client/src/app/address/AddressPageContent.tsx
  apps/client/src/app/address/page.tsx
  apps/client/src/app/order/confirm/OrderConfirmPageContent.tsx
  apps/client/src/app/order/confirm/page.tsx
  apps/client/src/app/order/form/OrderFormPageContent.tsx
  apps/client/src/app/order/form/page.tsx
  apps/client/src/components/common/SuspenseWrapper.tsx
  apps/client/src/hooks/useValidOrderFrom.ts
Labels: 🐛 bug

#44 Integration: 주문 기능 구현 및 관련 flow 및 컴포넌트 refactor
  apps/client/src/app/address/AddressPageContent.tsx
  apps/client/src/app/address/[type]/AddressTypePageContent.tsx
  apps/client/src/app/address/[type]/page.tsx
  apps/client/src/app/address/page.tsx
  apps/client/src/app/auth/terms/page.tsx
  apps/client/src/app/cart/page.tsx
  apps/client/src/app/globals.css
  apps/client/src/app/order/complete/page.tsx
  apps/client/src/app/order/confirm/OrderConfirmPageContent.tsx
  apps/client/src/app/order/confirm/page.tsx
  apps/client/src/app/order/form/OrderFormPageContent.tsx
  apps/client/src/app/order/form/page.tsx
  apps/client/src/components/common/BottomButton.tsx
  apps/client/src/components/common/CheckBox.tsx
  apps/client/src/components/common/SuspenseWrapper.tsx
  apps/client/src/components/features/cart/CartItem.tsx
  apps/client/src/components/features/cart/PurchaseNowButton.tsx
  apps/client/src/components/features/obje/BottomPurchaseCTA.tsx
  apps/client/src/components/features/obje/BottomSheet.tsx
  apps/client/src/components/features/order/OrderItem.tsx
  apps/client/src/components/features/order/OrderItemsSection.tsx
  apps/client/src/components/features/order/complete/PaymentMethod.tsx
  apps/client/src/components/features/order/form/AddressSection.tsx
  apps/client/src/components/features/order/form/AgreementSection.tsx
  apps/client/src/components/features/order/form/PriceSummarySection.tsx
  apps/client/src/components/features/order/form/TermsSection.tsx
  apps/client/src/components/layouts/Header.tsx
  apps/client/src/constants/order.ts
  apps/client/src/constants/orderConfirm.ts
  apps/client/src/constants/orderNotifications.ts
  apps/client/src/constants/terms.ts
  apps/client/src/hooks/check/index.ts
  apps/client/src/hooks/check/useCheckGroup.ts
  apps/client/src/hooks/check/useTermsCheck.ts
  apps/client/src/hooks/mutations/useAddressMutation.ts
  apps/client/src/hooks/mutations/useOrderMutation.ts
  apps/client/src/hooks/queries/useOrderQuery.ts
  apps/client/src/hooks/stores/useBaseOrderRequestStore.ts
  apps/client/src/hooks/stores/useSelectedAddressIdStore.ts
  apps/client/src/hooks/stores/useSelectedAddressStore.ts
  apps/client/src/hooks/stores/useSelectedProductsStore.ts
  apps/client/src/hooks/useValidOrderFrom.ts
  apps/client/src/schemas/address.ts
  apps/client/src/schemas/object.ts
  apps/client/src/schemas/objectDetail.ts
  apps/client/src/schemas/order.ts
  apps/client/src/schemas/schema.d.ts
  apps/client/src/schemas/terms.ts
  apps/client/src/schemas/utils/validate.ts
  apps/client/src/services/api/address.ts
  apps/client/src/services/api/order.ts
  apps/client/src/utils/cart/getCart.ts
  apps/client/src/utils/order/getPrice.ts
  apps/client/src/utils/route.ts
  apps/client/vercel.json
Labels: ✨ feature, ♻️ refactor, ⛓️‍💥 API

#36 Feat: 오브제 보드 필터링 및 페이지네이션
  apps/client/package.json
  apps/client/src/app/filter/layout.tsx
  apps/client/src/app/filter/page.tsx
  apps/client/src/app/main/page.tsx
  apps/client/src/components/common/BottomButton.tsx
  apps/client/src/components/features/filter/ChipList.tsx
  apps/client/src/components/features/filter/PriceRange.tsx
  apps/client/src/components/features/main/ObjectBoard.tsx
  apps/client/src/components/features/main/ProductList.tsx
  apps/client/src/components/features/main/ProductListToolbar.tsx
  apps/client/src/constants/filter.ts
  apps/client/src/constants/filterList.ts
  apps/client/src/schemas/object.ts
  pnpm-lock.yaml
Labels: ✨ feature, 📷 UI

#51 Feat: 마이페이지 메인 & 1:1 문의 페이지 구현
  apps/client/next.config.ts
  apps/client/public/mypage-banner.svg
  apps/client/public/profile/default.svg
  apps/client/src/app/(comming-soon)/mypage/edit/page.tsx
  apps/client/src/app/(comming-soon)/mypage/order-list/page.tsx
  apps/client/src/app/(comming-soon)/mypage/return-list/page.tsx
  apps/client/src/app/main/page.tsx
  apps/client/src/app/mypage/(with-footer)/layout.tsx
  apps/client/src/app/mypage/(with-footer)/page.tsx
  apps/client/src/app/mypage/contact/page.tsx
  apps/client/src/app/mypage/leave/page.tsx
  apps/client/src/app/mypage/page.tsx
  apps/client/src/app/order/form/OrderFormPageContent.tsx
  apps/client/src/assets/mypage/heart.svg
  apps/client/src/components/common/ClipboardCopyToast.tsx
  apps/client/src/components/features/mypage/AccountActionButton.tsx
  apps/client/src/components/features/mypage/ButtonSection.tsx
  apps/client/src/components/features/mypage/CustomLink.tsx
  apps/client/src/components/features/mypage/HighlightCard.tsx
  apps/client/src/components/features/mypage/LogoutButton.tsx
  apps/client/src/components/features/mypage/NavigationSection.tsx
  apps/client/src/components/features/mypage/Profile.tsx
  apps/client/src/components/features/mypage/contact/ChannelButton.tsx
  apps/client/src/components/features/mypage/contact/ChannelSection.tsx
  apps/client/src/components/features/mypage/contact/NoificationSection.tsx
  apps/client/src/components/layouts/Footer.tsx
  apps/client/src/components/layouts/Frame.tsx
  apps/client/src/constants/footer.ts
  apps/client/src/constants/mypage.ts
  apps/client/src/constants/user.ts
  apps/client/src/hooks/actions/useClipboardCopy.ts
  apps/client/src/hooks/queries/useUserQuery.ts
  apps/client/src/icons/Chevron.ts
  apps/client/src/icons/Mypage.ts
  apps/client/src/schemas/user.ts
  apps/client/src/services/api/auth.ts
  apps/client/src/services/api/user.ts
  apps/client/src/utils/openMailApp.ts
Labels: ✨ feature, 📷 UI, ⛓️‍💥 API

#58 Release(0.2.0): 카카오 프로필 이미지 프로토콜 추가
  apps/client/next.config.ts
Labels: 🐛 bug

#60 Feat: LIKE 페이지 UI
  apps/client/public/about/logo.svg
  apps/client/public/about/loop.svg
  apps/client/public/about/point.svg
  apps/client/public/cart-item.jpg
  apps/client/public/checkbox/checked.svg
  apps/client/public/checkbox/unchecked.svg
  apps/client/public/checked-check.svg
  apps/client/public/obje-detail.jpg
  apps/client/public/obje-thumbnail.jpg
  apps/client/src/app/address/[type]/page.tsx
  apps/client/src/app/like/layout.tsx
  apps/client/src/app/like/page.tsx
  apps/client/src/app/order/confirm/OrderConfirmPageContent.tsx
  apps/client/src/app/robots.ts
  apps/client/src/app/sitemap.ts
  apps/client/src/assets/auth/check-circle-complete.svg
  apps/client/src/assets/common/alert.svg
  apps/client/src/assets/common/chevron-down.svg
  apps/client/src/assets/header/back.svg
  apps/client/src/assets/header/cart.svg
  apps/client/src/assets/header/close.svg
  apps/client/src/assets/header/loopz.svg
  apps/client/src/assets/header/search.svg
  apps/client/src/assets/mypage/heart.svg
  apps/client/src/assets/navigation-bar/loopz-book.svg
  apps/client/src/assets/navigation-bar/main.svg
  apps/client/src/assets/navigation-bar/my.svg
  apps/client/src/assets/navigation-bar/shot.svg
  apps/client/src/assets/object-board/filter.svg
  apps/client/src/assets/order-complete/gift.svg
  apps/client/src/components/common/CheckBox.tsx
  apps/client/src/components/common/filter/FilterBar.tsx
  apps/client/src/components/common/filter/unit/FilterEntryButton.tsx
  apps/client/src/components/common/filter/unit/SoldoutFilter.tsx
  apps/client/src/components/common/filter/unit/SortSelector.tsx
  apps/client/src/components/features/like/ObjectTab.tsx
  apps/client/src/components/features/like/SnapTab.tsx
  apps/client/src/components/features/like/TabBar.tsx
  apps/client/src/components/features/main/Banner.tsx
  apps/client/src/components/features/main/MoreList.tsx
  apps/client/src/components/features/main/ObjectBoard.tsx
  apps/client/src/components/features/main/ProductList.tsx
  apps/client/src/components/features/main/ProductList/ProductItem.tsx
  apps/client/src/components/features/main/ProductList/index.tsx
  apps/client/src/components/features/main/ProductListToolbar.tsx
  apps/client/src/components/features/mypage/CustomLink.tsx
  apps/client/src/components/features/order/form/AddressSection.tsx
  apps/client/src/components/features/order/form/PriceSummarySection.tsx
  apps/client/src/components/icons/ChevronDown.ts
  apps/client/src/components/layouts/Frame.tsx
  apps/client/src/constants/like.ts
  apps/client/src/icons/Alert.ts
  apps/client/src/icons/Chevron.ts
  apps/client/src/icons/Filter.ts
  apps/client/src/icons/Gift.ts
  apps/client/src/icons/ObjectBoard.ts
  apps/client/vercel.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: ✨ feature, 📷 UI

#70 Feat: 마이페이지 주문/취소/반품 관련 컴포넌트 구현
  apps/client/src/app/(comming-soon)/mypage/order-list/page.tsx
  apps/client/src/app/(comming-soon)/mypage/return-list/page.tsx
  apps/client/src/app/mypage/order-detail/[id]/page.tsx
  apps/client/src/app/mypage/order-list/page.tsx
  apps/client/src/app/mypage/return-detail/[id]/page.tsx
  apps/client/src/app/mypage/return-form/page.tsx
  apps/client/src/app/mypage/return-list/page.tsx
  apps/client/src/components/common/Radio.tsx
  apps/client/src/components/features/mypage/Divider.tsx
  apps/client/src/components/features/mypage/ProductItemByDeliveryState.tsx
  apps/client/src/components/features/mypage/detail/DetailTitle.tsx
  apps/client/src/components/features/mypage/detail/PaymentSummary.tsx
  apps/client/src/components/features/mypage/order-detail/ReceiptInformation.tsx
  apps/client/src/components/features/mypage/return-detail/ReturnDetail.tsx
  apps/client/src/components/features/mypage/return-form/AccountInformation.tsx
  apps/client/src/components/features/mypage/return-form/CustomInput.tsx
  apps/client/src/components/features/mypage/return-form/PhoneNumberInformation.tsx
  apps/client/src/components/features/mypage/return-form/RadioSection.tsx
  apps/client/src/components/features/mypage/return-form/ReturnProductItem.tsx
  apps/client/src/constants/deliveryState.ts
  apps/client/src/constants/return.ts
Labels: ✨ feature, 📷 UI

#72 Fix: 주문 Flow
  apps/client/src/app/address/AddressPageContent.tsx
  apps/client/src/app/address/[type]/page.tsx
  apps/client/src/app/address/page.tsx
  apps/client/src/app/auth/nickname/page.tsx
  apps/client/src/app/auth/terms/page.tsx
  apps/client/src/app/cart/page.tsx
  apps/client/src/app/oauth/google/GoogleRedirectClient.tsx
  apps/client/src/app/oauth/kakao/KakaoRedirectClient.tsx
  apps/client/src/app/order/complete/layout.tsx
  apps/client/src/app/order/complete/page.tsx
  apps/client/src/app/order/confirm/OrderConfirmPageContent.tsx
  apps/client/src/app/order/confirm/page.tsx
  apps/client/src/app/order/form/OrderFormPageContent.tsx
  apps/client/src/app/order/form/page.tsx
  apps/client/src/auth/cookie/setCookie.ts
  apps/client/src/components/features/cart/CartItem.tsx
  apps/client/src/components/features/cart/PurchaseNowButton.tsx
  apps/client/src/components/features/obje/BottomSheet.tsx
  apps/client/src/components/features/order/OrderItem.tsx
  apps/client/src/components/features/order/OrderItemsSection.tsx
  apps/client/src/components/features/order/form/AddressSection.tsx
  apps/client/src/hooks/mutations/useOrderMutation.ts
  apps/client/src/hooks/queries/useObjectQuery.ts
  apps/client/src/hooks/queries/useOrderQuery.ts
  apps/client/src/hooks/stores/useBaseOrderRequestStore.ts
  apps/client/src/hooks/stores/useSelectedAddressIdStore.ts
  apps/client/src/hooks/stores/useSelectedProductsStore.ts
  apps/client/src/hooks/stores/useUserInfoStore.ts
  apps/client/src/hooks/useValidOrderFrom.ts
  apps/client/src/schemas/address.ts
  apps/client/src/schemas/object/object.ts
  apps/client/src/schemas/order.ts
  apps/client/src/schemas/utils/validate.ts
  apps/client/src/services/api/address.ts
  apps/client/src/services/api/object.ts
  apps/client/src/services/api/order.ts
  apps/client/src/utils/order/getPrice.ts
  apps/client/src/utils/route.ts
Labels: ♻️ refactor, 🧑‍🔧 fix, ⛓️‍💥 API

#73 Feat: 마이페이지 주문/취소/반품 내역 페이지 구현
  apps/client/package.json
  apps/client/public/alert.svg
  apps/client/public/complete.svg
  apps/client/src/app/layout.tsx
  apps/client/src/app/mypage/order-detail/[id]/page.tsx
  apps/client/src/app/mypage/order-list/page.tsx
  apps/client/src/app/mypage/return-detail/[id]/page.tsx
  apps/client/src/app/mypage/return-form/[type]/complete/page.tsx
  apps/client/src/app/mypage/return-form/[type]/reasons/page.tsx
  apps/client/src/app/mypage/return-form/[type]/refund-account/page.tsx
  apps/client/src/app/mypage/return-list/page.tsx
  apps/client/src/components/common/Modal.tsx
  apps/client/src/components/features/mypage/ProductItemByDeliveryState.tsx
  apps/client/src/components/features/mypage/detail/PaymentSummary.tsx
  apps/client/src/components/features/mypage/list/NoItem.tsx
  apps/client/src/components/features/mypage/list/TabBar.tsx
  apps/client/src/components/features/mypage/order-detail/OrderPaymentSummary.tsx
  apps/client/src/components/features/mypage/return-detail/ReturnDetail.tsx
  apps/client/src/components/features/mypage/return-detail/ReturnPaymentSummary.tsx
  apps/client/src/components/features/mypage/return-form/RefundPolicy.tsx
  apps/client/src/constants/deliveryState.ts
  apps/client/src/constants/mypage.ts
  apps/client/src/constants/return.ts
  apps/client/src/providers/OverlayProviderWrapper.tsx
  pnpm-lock.yaml
Labels: ✨ feature, 📷 UI

#86 Feat: 결제 시스템 도입
  apps/client/next.config.ts
  apps/client/package.json
  apps/client/src/app/my-order/cs-request/form/[orderNumber]/page.tsx
  apps/client/src/app/order/complete/page.tsx
  apps/client/src/app/order/confirm/page.tsx
  apps/client/src/app/order/form/page.tsx
  apps/client/src/app/payment/notification/page.tsx
  apps/client/src/app/payment/redirect/layout.tsx
  apps/client/src/app/payment/redirect/page.tsx
  apps/client/src/components/features/order/complete/PaymentMethod.tsx
  apps/client/src/constants/order/order.ts
  apps/client/src/hooks/actions/useOrderStatusCTAHandlers.tsx
  apps/client/src/hooks/mutations/useOrderMutation.ts
  apps/client/src/hooks/mutations/usePaymentMutation.ts
  apps/client/src/hooks/stores/useBaseOrderRequestStore.ts
  apps/client/src/middleware.ts
  apps/client/src/schemas/address.ts
  apps/client/src/schemas/order/enum.ts
  apps/client/src/schemas/order/order.ts
  apps/client/src/schemas/payment/enum.ts
  apps/client/src/schemas/payment/gatewayOptions.ts
  apps/client/src/schemas/payment/options.ts
  apps/client/src/schemas/payment/request.ts
  apps/client/src/schemas/utils/prefixedUuidSchema.ts
  apps/client/src/services/api/order.ts
  apps/client/src/services/api/payment/completePayment.ts
  apps/client/src/services/api/payment/index.ts
  apps/client/src/services/api/payment/placePayment.ts
  apps/client/src/services/api/payment/types.ts
  apps/client/src/utils/order/getOrderName.ts
  apps/client/src/utils/order/getRandomId.ts
  apps/client/vercel.json
  pnpm-lock.yaml
Labels: ✨ feature, ⛓️‍💥 API
